<?php $_code=$this->getMethodCode() ?>
<script src="<?php echo Mage::getDesign()->getSkinUrl('paymill/jquery.min.js'); ?>"></script>
<link rel="stylesheet" type="text/css" href="<?php echo Mage::getDesign()->getSkinUrl('paymill/paymill_styles.css'); ?>" />
<!--
    The payment form.
    Important: do not process any card data to the server (leave name attribute away)
-->
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display: none">
    <li>
        <img src="<?php echo Mage::getDesign()->getSkinUrl('paymill/icon_elv.png'); ?>" />
    </li>
    <?php if (is_null(Mage::getSingleton("paymillelv/customerdata")->loadByUserId(Mage::getSingleton('customer/session')->getCustomer()->getId()))): ?>
    <li>
        <label for="paymillelv_accountholder" class="required"><em>*</em>Kontoinhaber</label>
        <div class="input-box">
            <input type="text" class="input-text required-entry" id="paymillelv_accountholder" value="" autocomplete="off">
            <div class="validation-advice" id="accountholder_error" style="display: none"></div>
        </div>
    </li>
    <li>
        <label for="paymillelv_accountnumber" class="required"><em>*</em>Kontonummer</label>
        <div class="input-box">
            <input type="text" id="paymillelv_accountnumber" class="input-text" value="" autocomplete="off">
            <div class="validation-advice" id="accountnumber_error" style="display: none"></div>
        </div>
    </li>
    <li>
        <label for="paymillelv_banknumber" class="required"><em>*</em>Bankleitzahl</label>
        <div class="input-box">
            <input type="text" id="paymillelv_banknumber" class="input-text" autocomplete="off" value="">
            <div class="validation-advice" id="banknumber_error" style="display: none"></div>
        </div>
    </li>
    <?php endif; ?>
    <?php if (!is_null(Mage::getSingleton("paymillelv/customerdata")->loadByUserId(Mage::getSingleton('customer/session')->getCustomer()->getId()))): ?>
    <input type="hidden" id="paymill_elv_existing_customer" value="true">
    <?php elseif (is_null(Mage::getSingleton("paymillelv/customerdata")->loadByUserId(Mage::getSingleton('customer/session')->getCustomer()->getId()))): ?>
    <input type="hidden" id="paymill_elv_existing_customer" value="false">
    <?php endif; ?>
    <!-- this gets the transaction token -->
    <input type="hidden" id="paymill_elv_transaction_token" type="text" value="" name="payment[paymill_elv_transaction_token]" />
    <?php if ($this->showPaymillLabel) { ?>
    <li>
        <div class="paymill_powered"><div class="paymill_credits">Sicheres Lastschriftverfahren powered by <a href="http://www.paymill.de" target="_blank">Paymill</a></div></div>
    </li>
    <?php } ?>
</ul>
<!--
PaymillPaymentELV
API enpoint: <?php print $this->paymillApiEndpoint; ?>
-->
<script type="text/javascript">
    var PAYMILL_PUBLIC_KEY = '<?php print $this->paymillPublicApiKey; ?>';
</script>
<script type="text/javascript" src="<?php print $this->paymillBridgeEndpoint; ?>"></script>
<script type="text/javascript">
    jQuery.noConflict();

    jQuery(document).ready(function(){
        jQuery('#payment-buttons-container button:first').prop("onclick", null);
        jQuery('#payment-buttons-container button:first').unbind('click');
        jQuery('#payment-buttons-container button:first').click(paymill_payment_save_override);
    });

    if (typeof paymill_payment_save_override != 'function') {
        function paymill_payment_save_override() {
            if (payment.currentMethod == "paymillcc") {
                if (jQuery('#paymill_existing_customer').val() == 'false') {
                    paymill_cc_payment_save_override();
                } else {
                    payment.save();
                }
            } else if (payment.currentMethod == "paymillelv") {
                if (jQuery('#paymill_elv_existing_customer').val() == 'false') {
                    paymill_elv_payment_save_override();
                } else {
                    payment.save();
                }
            } else {
                payment.save();
            }
        }
    }

    // is paymillPayment?
    function paymill_is_paymill_elv_payment() {
        return payment.currentMethod == "<?php print $_code; ?>";
    }

    // handler that is called when click on next step button
    function paymill_elv_payment_save_override() {
        if (paymill_is_paymill_elv_payment()) {
            paymill_elv_debug('Paymill elv payment method triggered');
            if (paymill_elv_validate()) {
                paymill_elv_debug('Validation successful');
                var accountholder = jQuery('#paymillelv_accountholder');
                var accountnumber = jQuery('#paymillelv_accountnumber');
                var banknumber = jQuery('#paymillelv_banknumber');
                paymill.createToken({
                    number: accountnumber.val(),
                    bank: banknumber.val(),
                    accountholder: accountholder.val(),
                    }, paymill_elv_response_handler
                );
            }
        } else {
            payment.save();
        }
    }

    // paymill response handler
    function paymill_elv_response_handler(error, result) {
        paymill_elv_debug('Start Paymill response handler');
        if (error) {
            alert("API returned error" + error.apierror);
            paymill_elv_debug('An API error occured ' + error.apierror);
        } else {
            paymill_elv_debug('Received a token: ' + result.token);
            jQuery('#paymill_elv_transaction_token').val(result.token);
            payment.save();
        }
    }

    // validation
    function paymill_elv_validate() {

        var accountholder = jQuery('#paymillelv_accountholder');
        var accountnumber = jQuery('#paymillelv_accountnumber');
        var banknumber = jQuery('#paymillelv_banknumber');
        var banknumber_error = jQuery('#banknumber_error');
        var accountnumber_error = jQuery('#accountnumber_error');
        var accountholder_error = jQuery('#accountholder_error');

        var result = true;

        paymill_elv_debug('Start form validation');

        // reset errors
        banknumber_error.hide();
        accountnumber_error.hide();
        accountholder_error.hide();

        // error messages
        error_msg_accountholder_missing = "<?php echo Mage::helper('paymillelv')->__("The account holder is missing"); ?>";
        error_msg_accountnumber_invalid = "<?php echo Mage::helper('paymillelv')->__("The account number is invalid"); ?>"
        error_msg_banknumber_invalid = "<?php echo Mage::helper('paymillelv')->__("The bank code is invalid"); ?>"

        if (accountholder.val() == "") {
            accountholder_error.html(error_msg_accountholder_missing).show();
            accountholder.addClass('validation-failed');
            result = false;
        } else {
            accountholder.removeClass('validation-failed');
        }

        if (!paymill.validateAccountNumber(accountnumber.val())) {
            accountnumber_error.html(error_msg_accountnumber_invalid).show();
            accountnumber.addClass('validation-failed');
            result = false;
        } else {
            accountnumber.removeClass('validation-failed');
        }

        if (!paymill.validateBankCode(banknumber.val())) {
            banknumber_error.html(error_msg_banknumber_invalid).show();
            banknumber.addClass('validation-failed');
            result = false;
        } else {
            banknumber.removeClass('validation-failed');
        }

        return result;
    }

    // debug mode
    function paymill_elv_debug(message) {
        if (<?php print $this->paymillDebugMode; ?>) {
            console.log("[PaymillELV] " + message);
        }
    }

</script>


