<?php $_code=$this->getMethodCode() ?>
<script type="text/javascript" src="<?php echo $this->getDataHelper()->getJscriptPath()."paymentForm.js"?>"></script>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <p class="paymill-payment-errors alert-error" style="display:none;"></p>
    </li>
    <li>
        <label class="card-number-label">
            <?php echo $this->__("paymill_Number") ?>
        </label>
    </li>            
    <li>
        <input class="card-number" type="text" size="20" value="4111111111111111"/>
    </li>            
    <li>
        <label class="card-cvc-label">
            <?php echo $this->__("paymill_Cvc") ?>
        </label>
    </li>
    <li>
        <input class="card-cvc" type="text" size="4" value="111"/>
    </li>
    <li>
        <div class="card-icon"></div>
    </li>
    <li>
        <label class="card-holdername-label">
            <?php echo $this->__("paymill_Holder") ?>
        </label>
    </li>
    <li>
        <input class="card-holdername" type="text" size="20" value="lala"/>
    </li>
    <li>
        <label class="card-expiry-label">
                <?php echo $this->__("paymill_Date") ?>
        </label>
    </li>
    <li> 
        <div>
            <input class="card-expiry-month" type="text" size="2" value="12"/>
            <span> / </span>
            <input class="card-expiry-year" type="text" size="4" value="2015"/>
        </div>
    </li>
    <li>
        <input class="paymill-payment-name"          name="payment[paymill-payment-name]"          id="payment[paymill-payment-name]"          type="hidden" value="<?php echo $this->getMethodCode()?>"                                  />
        <input class="paymill-payment-token"         name="payment[paymill-payment-token]"         id="payment[paymill-payment-token]"         type="hidden" value=""                                                                     />
        <input class="paymill-payment-amount"        name="payment[paymill-payment-amount]"        id="payment[paymill-payment-amount]"        type="hidden" value="<?php echo $this->getPaymentHelper()->getAmount() ?>"                 />
        <input class="paymill-payment-currency"      name="payment[paymill-payment-currency]"      id="payment[paymill-payment-currency]"      type="hidden" value="<?php echo $this->getPaymentHelper()->getCurrency() ?>"               />
        <input class="paymill-option-debug"          name="payment[paymill-option-debug]"          id="payment[paymill-option-debug]"          type="hidden" value="<?php echo $this->getDataHelper()->isInDebugMode() ?>"                />
        <input class="paymill-option-logo"           name="payment[paymill-option-logo]"           id="payment[paymill-option-logo]"           type="hidden" value="<?php echo $this->getDataHelper()->isShowingLabels() ?>"              />
        <input class="paymill-info-image-path"       name="payment[paymill-info-image-path]"       id="payment[paymill-info-image-path]"       type="hidden" value="<?php echo $this->getDataHelper()->getImagePath() ?>"                 />
        <input class="paymill-info-public_key"       name="payment[paymill-info-public_key]"       id="payment[paymill-info-public_key]"       type="hidden" value="<?php echo $this->getDataHelper()->getPublicKey() ?>"                 />
        <input class="paymill-payment-error-number"  name="payment[paymill-payment-error-number]"  id="payment[paymill-payment-error-number]"  type="hidden" value="<?php echo $this->__("paymill_error_text_invalid_number_cc") ."<br/>\n" ?>"/>
        <input class="paymill-payment-error-holder"  name="payment[paymill-payment-error-holder]"  id="payment[paymill-payment-error-holder]"  type="hidden" value="<?php echo $this->__("paymill_error_text_invalid_holder_cc") ."<br/>\n" ?>"/>
        <input class="paymill-payment-error-expdate" name="payment[paymill-payment-error-expdate]" id="payment[paymill-payment-error-expdate]" type="hidden" value="<?php echo $this->__("paymill_error_text_invalid_expdate")   ."<br/>\n" ?>"/>
    </li>
</ul>