<?php $_code=$this->getMethodCode() ?>
<script type="text/javascript" src="<?php echo $this->getDataHelper()->getJscriptPath()."paymentForm.js"?>"></script>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <li>
        <p class="paymill-payment-errors alert-error" style="display:none;"></p>
    </li>
    <li>
        <label class="elv-account-label">
            <?php echo $this->__("paymill_account") ?>
        </label>
    </li>            
    <li>
        <input class="elv-account" type="text" size="20" value="1234567890"/>
    </li>            
    <li>
        <label class="elv-bankcode-label">
            <?php echo $this->__("paymill_bankcode") ?>
        </label>
    </li>
    <li>
        <input class="elv-bankcode" type="text" size="20" value="99999999"/>
    </li>
    <li>
        <label class="elv-holdername-label">
            <?php echo $this->__("paymill_Holder") ?>
        </label>
    </li>
    <li>
        <input class="elv-holdername" type="text" size="20" value="Max Mustermann"/>
    </li>
    <?php if($this->getDataHelper()->isShowingLabels()){ echo "<li><div class='paymill_powered'><div class='paymill_credits'>Sichere Kreditkartenzahlung powered by <a href='http://www.paymill.de' target='_blank'>Paymill</a></div></div></li>";} ?>
    <li>
        <input class="paymill-payment-name"          name="payment[paymill-payment-name]"          id="payment[paymill-payment-name]"          type="hidden" value="<?php echo $this->getMethodCode()?>"                                  />
        <input class="paymill-payment-token"         name="payment[paymill-payment-token]"         id="payment[paymill-payment-token]"         type="hidden" value=""                                                                     />
        <input class="paymill-payment-amount"        name="payment[paymill-payment-amount]"        id="payment[paymill-payment-amount]"        type="hidden" value="<?php echo $this->getPaymentHelper()->getAmount() ?>"                 />
        <input class="paymill-payment-currency"      name="payment[paymill-payment-currency]"      id="payment[paymill-payment-currency]"      type="hidden" value="<?php echo $this->getPaymentHelper()->getCurrency() ?>"               />
        <input class="paymill-option-debug"          name="payment[paymill-option-debug]"          id="payment[paymill-option-debug]"          type="hidden" value="<?php echo $this->getDataHelper()->isInDebugMode() ?>"                />
        <input class="paymill-info-image-path"       name="payment[paymill-info-image-path]"       id="payment[paymill-info-image-path]"       type="hidden" value="<?php echo $this->getDataHelper()->getImagePath() ?>"                 />
        <input class="paymill-info-public_key"       name="payment[paymill-info-public_key]"       id="payment[paymill-info-public_key]"       type="hidden" value="<?php echo $this->getDataHelper()->getPublicKey() ?>"                 />
        <input class="paymill-payment-error-number"  name="payment[paymill-payment-error-number]"  id="payment[paymill-payment-error-number]"  type="hidden" value="<?php echo $this->__("paymill_error_text_invalid_number_elv") ."<br/>\n" ?>"/>
        <input class="paymill-payment-error-holder"  name="payment[paymill-payment-error-holder]"  id="payment[paymill-payment-error-holder]"  type="hidden" value="<?php echo $this->__("paymill_error_text_invalid_holder_elv") ."<br/>\n" ?>"/>
        <input class="paymill-payment-error-bankcode" name="payment[paymill-payment-error-bankcode]" id="payment[paymill-payment-error-bankcode]" type="hidden" value="<?php echo $this->__("paymill_error_text_invalid_bankcode")   ."<br/>\n" ?>"/>
    </li>
</ul>